// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.1
// source: protocol/pb/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType 枚举
type MessageType int32

const (
	MessageType_REQUEST  MessageType = 0
	MessageType_RESPONSE MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "REQUEST",
		1: "RESPONSE",
	}
	MessageType_value = map[string]int32{
		"REQUEST":  0,
		"RESPONSE": 1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_pb_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_protocol_pb_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_pb_message_proto_rawDescGZIP(), []int{0}
}

// Header 消息头
type PBHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   MessageType            `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=pb.MessageType" json:"message_type,omitempty"`
	RequestId     uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MethodName    string                 `protobuf:"bytes,4,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	DataLen       uint32                 `protobuf:"varint,6,opt,name=data_len,json=dataLen,proto3" json:"data_len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBHeader) Reset() {
	*x = PBHeader{}
	mi := &file_protocol_pb_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBHeader) ProtoMessage() {}

func (x *PBHeader) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_pb_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBHeader.ProtoReflect.Descriptor instead.
func (*PBHeader) Descriptor() ([]byte, []int) {
	return file_protocol_pb_message_proto_rawDescGZIP(), []int{0}
}

func (x *PBHeader) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_REQUEST
}

func (x *PBHeader) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *PBHeader) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *PBHeader) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *PBHeader) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PBHeader) GetDataLen() uint32 {
	if x != nil {
		return x.DataLen
	}
	return 0
}

// Message 完整消息
type PBMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *PBHeader              `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBMessage) Reset() {
	*x = PBMessage{}
	mi := &file_protocol_pb_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBMessage) ProtoMessage() {}

func (x *PBMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_pb_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBMessage.ProtoReflect.Descriptor instead.
func (*PBMessage) Descriptor() ([]byte, []int) {
	return file_protocol_pb_message_proto_rawDescGZIP(), []int{1}
}

func (x *PBMessage) GetHeader() *PBHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PBMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_protocol_pb_message_proto protoreflect.FileDescriptor

var file_protocol_pb_message_proto_rawDesc = string([]byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0xd2, 0x01, 0x0a, 0x08, 0x50, 0x42, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x0c,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x64, 0x61, 0x74,
	0x61, 0x4c, 0x65, 0x6e, 0x22, 0x45, 0x0a, 0x09, 0x50, 0x42, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x24, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x42, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x28, 0x0a, 0x0b, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x53, 0x50, 0x4f,
	0x4e, 0x53, 0x45, 0x10, 0x01, 0x42, 0x19, 0x5a, 0x17, 0x6c, 0x69, 0x73, 0x65, 0x6e, 0x2f, 0x6c,
	0x2d, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_protocol_pb_message_proto_rawDescOnce sync.Once
	file_protocol_pb_message_proto_rawDescData []byte
)

func file_protocol_pb_message_proto_rawDescGZIP() []byte {
	file_protocol_pb_message_proto_rawDescOnce.Do(func() {
		file_protocol_pb_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_pb_message_proto_rawDesc), len(file_protocol_pb_message_proto_rawDesc)))
	})
	return file_protocol_pb_message_proto_rawDescData
}

var file_protocol_pb_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocol_pb_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocol_pb_message_proto_goTypes = []any{
	(MessageType)(0),  // 0: pb.MessageType
	(*PBHeader)(nil),  // 1: pb.PBHeader
	(*PBMessage)(nil), // 2: pb.PBMessage
}
var file_protocol_pb_message_proto_depIdxs = []int32{
	0, // 0: pb.PBHeader.message_type:type_name -> pb.MessageType
	1, // 1: pb.PBMessage.header:type_name -> pb.PBHeader
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protocol_pb_message_proto_init() }
func file_protocol_pb_message_proto_init() {
	if File_protocol_pb_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_pb_message_proto_rawDesc), len(file_protocol_pb_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_pb_message_proto_goTypes,
		DependencyIndexes: file_protocol_pb_message_proto_depIdxs,
		EnumInfos:         file_protocol_pb_message_proto_enumTypes,
		MessageInfos:      file_protocol_pb_message_proto_msgTypes,
	}.Build()
	File_protocol_pb_message_proto = out.File
	file_protocol_pb_message_proto_goTypes = nil
	file_protocol_pb_message_proto_depIdxs = nil
}
